name: packfs

on: workflow_dispatch

jobs:
  packfs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install prerequisites for xz autogen
        run: sudo apt-get update && sudo apt-get install autopoint po4a gdb strace
      
      - name: Build
        run: make
      
      - name: Test zip
        run: |
          zip -r packfs.zip packfs.c .git
          LD_PRELOAD=$PWD/libpackfs.so /usr/bin/cat packfs.zip/packfs.c
          LD_PRELOAD=$PWD/libpackfs.so /usr/bin/stat packfs.zip/packfs.c
          LD_PRELOAD=$PWD/libpackfs.so PACKFS_ARCHIVES=packfs.zip /usr/bin/cat /packfs/packfs.c
          LD_PRELOAD=$PWD/libpackfs.so /usr/bin/ls -lah packfs.zip/packfs.c
          LD_PRELOAD=$PWD/libpackfs.so /usr/bin/ls -lah packfs.zip
          LD_PRELOAD=$PWD/libpackfs.so /usr/bin/find packfs.zip

          #python packfs.py -i .git -o packfs.h --prefix=/packfs/dotgit --ld=ld

          mkdir test && echo aa > test/a.txt && zip -r testa.zip test && rm -rf test
          mkdir test && echo bb > test/b.txt && zip -r testb.zip test && rm -rf test
          LD_PRELOAD=$PWD/libpackfs.so PACKFS_ARCHIVES=testa.zip@/packfstest:testb.zip@/packfstest /usr/bin/find /packfstest
          
          mkdir test && mv testa.zip testb.zip test
          LD_PRELOAD=$PWD/libpackfs.so PACKFS_ARCHIVESDIRS=test /usr/bin/find /packfs
          
          echo '[{"path" : "test/", "size": 0, "offset": 0}, {"path" : "test/a.txt", "size": 3, "offset": 0}]' > test/testa.zip.json
          LD_PRELOAD=$PWD/libpackfs.so PACKFS_LISTINGS=test/testa.zip.json /usr/bin/find /packfs
      
      #- name: Test xz
      #  run: |
      #    #sudo apt install ltrace && ltrace /usr/bin/find .git
      #    tar -cJf packfs.tar.xz packfs.c .git
      #    LD_PRELOAD=$PWD/libpackfs.so /usr/bin/cat packfs.tar.xz/packfs.c
      #    LD_PRELOAD=$PWD/libpackfs.so /usr/bin/stat packfs.tar.xz/packfs.c
      #    LD_PRELOAD=$PWD/libpackfs.so /usr/bin/ls -lah packfs.tar.xz
      #    LD_PRELOAD=$PWD/libpackfs.so /usr/bin/ls -lah packfs.tar.xz/packfs.c
      #    LD_PRELOAD=$PWD/libpackfs.so /usr/bin/find packfs.tar.xz
       
      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            libpackfs.so
      #      packfs.h
      #      packfs.h.txt
